# Generated by Django 2.2 on 2021-11-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('java_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javashop',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='java_shops',
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='java_app.JavaShop'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='java_app.User'),
        ),
    ]
