# Generated by Django 2.2 on 2021-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java_app', '0002_auto_20211114_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javashop',
            name='hours_of_operation',
            field=models.CharField(max_length=100),
        ),
    ]
